name: Daily Content Update

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 00:00 运行
  workflow_dispatch:  # 允许手动触发

jobs:
  update-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Generate daily content
        env:
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}  # 将 DeepSeek API 密钥存储在 GitHub Secrets 中
        run: |
          import requests
          import os

          # DeepSeek API 配置
          API_KEY = os.environ['DEEPSEEK_API_KEY']
          BASE_URL = "https://api.deepseek.com"

          # 调用 DeepSeek API 生成内容
          url = f"{BASE_URL}/v1/chat/completions"
          headers = {
              "Authorization": f"Bearer {API_KEY}",
              "Content-Type": "application/json"
          }
          data = {
              "model": "deepseek-chat",
              "messages": [
                  {"role": "system", "content": "你是一个英文口语老师，帮助用户学习日常英文表达。"},
                  {"role": "user", "content": "生成一条关于旅行的日常英文口语表达，并附带中文翻译和使用场景示例。"}
              ],
              "max_tokens": 150
          }
          response = requests.post(url, headers=headers, json=data)
          if response.status_code == 200:
              content = response.json()['choices'][0]['message']['content']
              with open("daily_content.txt", "w") as file:
                  file.write(content)
          else:
              print("API 调用失败:", response.text)

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add daily_content.txt
          git commit -m "Update daily content"
          git push
